services:
  - type: web
    name: atlanticproxy-backend
    env: go
    region: oregon
    plan: starter
    buildCommand: |
      cd scripts/proxy-client
      go build -tags netgo -ldflags '-s -w' -o app ./cmd/service
    startCommand: ./scripts/proxy-client/app
    envVars:
      - key: PORT
        value: 8082
      - key: ENV
        value: production
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
